001:
  code: 001
  name: "Travel Card Holder"
  price: 9.25

002:
  code: 002
  name: "Personalised Cufflinks"
  price: 45.00

003:
  code: 003
  name: "Kids T-Shirt"
  price: 19.95

004:
  code: 004
  name: "Test Product"
  price: 10.00
