001:
  code: 001
  name: "Travel Card Holder"
  price: 9.25
  currency: "GBP"

002:
  code: 002
  name: "Personalised Cufflinks"
  price: 45.00
  currency: "GBP"

003:
  code: 003
  name: "Kids T-Shirt"
  price: 19.95
  currency: "GBP"
